# Prefix
unbind C-b
set -g repeat-time 256
set -g prefix `
bind ` send-prefix

# Mouse support
set -g mouse on

# Buffer history
set -g history-limit 65536

# Enable colors
set -g default-terminal "tmux-256color"

# Vim lag
set -sg escape-time 0
